services: 
  demo-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  shorturl:
    image: shorturl/shorturl
    depends_on:
      - demo-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-dev
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=shorturl
      - DATABASE_PORT=3306